// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABXNcMbK94exoxl2soeirsnxij_mae4ZI',
    appId: '1:629808406364:web:9b14bb3559ee2c65d42b99',
    messagingSenderId: '629808406364',
    projectId: 'quit-smoking-tracker-fayy',
    authDomain: 'quit-smoking-tracker-fayy.firebaseapp.com',
    storageBucket: 'quit-smoking-tracker-fayy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCPEfiyg8_bu8Olsgr6XQLa-fNEp__e6c',
    appId: '1:629808406364:android:46c2c70cb5a539f3d42b99',
    messagingSenderId: '629808406364',
    projectId: 'quit-smoking-tracker-fayy',
    storageBucket: 'quit-smoking-tracker-fayy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCucQxs5X4am88IcriqZDkrkH4h8nmZUKg',
    appId: '1:629808406364:ios:bf1164790146f93ed42b99',
    messagingSenderId: '629808406364',
    projectId: 'quit-smoking-tracker-fayy',
    storageBucket: 'quit-smoking-tracker-fayy.firebasestorage.app',
    iosBundleId: 'com.example.quitSmokingTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCucQxs5X4am88IcriqZDkrkH4h8nmZUKg',
    appId: '1:629808406364:ios:bf1164790146f93ed42b99',
    messagingSenderId: '629808406364',
    projectId: 'quit-smoking-tracker-fayy',
    storageBucket: 'quit-smoking-tracker-fayy.firebasestorage.app',
    iosBundleId: 'com.example.quitSmokingTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABXNcMbK94exoxl2soeirsnxij_mae4ZI',
    appId: '1:629808406364:web:05c50657ae1efc30d42b99',
    messagingSenderId: '629808406364',
    projectId: 'quit-smoking-tracker-fayy',
    authDomain: 'quit-smoking-tracker-fayy.firebaseapp.com',
    storageBucket: 'quit-smoking-tracker-fayy.firebasestorage.app',
  );
}
